/*
 * input_mapping.h
 *
 *  Created on: Feb 4, 2017
 *      Author: root
 */

#ifndef ENGINE_INPUTMANAGER_INPUT_MAPPING_H_
#define ENGINE_INPUTMANAGER_INPUT_MAPPING_H_

#include <cstdint>


/* Mouse button masks */
#define MOUSE_BUTTON_LEFT						0x01
#define MOUSE_BUTTON_MIDDLE						0x02
#define MOUSE_BUTTON_RIGHT						0x03
#define MOUSE_BUTTON_WHEEL_UP					0x04
#define MOUSE_BUTTON_WHEEL_DOWN					0x05

/* Mouse button modifier masks */
#define MOUSE_BUTTON_MOD_NULL					0x0000
#define MOUSE_BUTTON_MOD_SHIFT					0x0001
#define MOUSE_BUTTON_MOD_CAPSLOCK				0x0002
#define MOUSE_BUTTON_MOD_CTRL					0x0004
#define MOUSE_BUTTON_MOD_LALT					0x0008
#define MOUSE_BUTTON_MOD_NUMLOCK				0x0010
#define MOUSE_BUTTON_MOD_SHIFT_CTRL				MOUSE_BUTTON_MOD_SHIFT | MOUSE_BUTTON_MOD_CTRL
#define MOUSE_BUTTON_MOD_SHIFT_LALT				MOUSE_BUTTON_MOD_SHIFT | MOUSE_BUTTON_MOD_LALT
#define MOUSE_BUTTON_MOD_CTRL_LALT				MOUSE_BUTTON_MOD_CTRL | MOUSE_BUTTON_MOD_LALT
#define MOUSE_BUTTON_MOD_SHIFT_CTRL_LALT		MOUSE_BUTTON_MOD_SHIFT_CTRL | MOUSE_BUTTON_MOD_LALT


enum class EMouseEvent : uint8_t {
	UNKNOWN										= 0,

	LMB_PRESS									= 1,
	MMB_PRESS									= 2,
	RMB_PRESS									= 3,

	LMB_RELEASE									= 11,
	MMB_RELEASE									= 12,
	RMB_RELEASE									= 13,

	WHEEL_UP									= 21,
	WHEEL_DOWN									= 22,

	LMB_SHIFT_PRESS								= 31,
	LMB_CTRL_PRESS								= 32,
	LMB_LALT_PRESS								= 33,
	LMB_SHIFT_CTRL_PRESS						= 34,
	LMB_SHIFT_LALT_PRESS						= 35,
	LMB_CTRL_LALT_PRESS							= 36,
	LMB_SHIFT_CTRL_LALT_PRESS					= 37,

	MMB_SHIFT_PRESS								= 41,
	MMB_CTRL_PRESS								= 42,
	MMB_LALT_PRESS								= 43,
	MMB_SHIFT_CTRL_PRESS						= 44,
	MMB_SHIFT_LALT_PRESS						= 45,
	MMB_CTRL_LALT_PRESS							= 46,
	MMB_SHIFT_CTRL_LALT_PRESS					= 47,

	RMB_SHIFT_PRESS								= 51,
	RMB_CTRL_PRESS								= 52,
	RMB_LALT_PRESS								= 53,
	RMB_SHIFT_CTRL_PRESS						= 54,
	RMB_SHIFT_LALT_PRESS						= 55,
	RMB_CTRL_LALT_PRESS							= 56,
	RMB_SHIFT_CTRL_LALT_PRESS					= 57,

	WHEEL_UP_SHIFT								= 91,
	WHEEL_UP_CTRL								= 92,
//	WHEEL_UP_LALT								= 93, cmon its too much
//	WHEEL_UP_SHIFT_CTRL							= 94,
//	WHEEL_UP_SHIFT_LALT							= 95,
//	WHEEL_UP_CTRL_LALT							= 96,
//	WHEEL_UP_SHIFT_CTRL_LALT					= 97,

	WHEEL_DOWN_SHIFT							= 101,
	WHEEL_DOWN_CTRL								= 102
//	WHEEL_DOWN_LALT								= 103,
//	WHEEL_DOWN_SHIFT_CTRL						= 104,
//	WHEEL_DOWN_SHIFT_LALT						= 105,
//	WHEEL_DOWN_CTRL_LALT						= 106,
//	WHEEL_DOWN_SHIFT_CTRL_LALT					= 107
};

#endif /* ENGINE_INPUTMANAGER_INPUT_MAPPING_H_ */
